<?php if (!empty($user["iduser"])) : ?>

    <div class="container mt-5 mx-auto">




        <div class="col-md-9  shadow  mx-auto py-4 px-5">
            <div class="row">
                <h4>DETAIL UŽIVATELE <?= $iduser ?></h4>
                <form method="POST" id="formupdate">
                    <div class="form-row ">

                        <div class="col-md-6  mt-3">
                            <input required name="jmeno" type="text" class="form-control" value="<?= isset($_POST["jmeno"]) ? $_POST["jmeno"] : ucfirst($user["firstname"]) ?>" placeholder="Jmeno">
                            <label class="text-danger" style="<?= isset($errorarray["err1"]) ? "display: inline" : "display: none;" ?>">Špatný formát.</label>
                        </div>

                        <div class="col-md-6  mt-3">
                            <input required name="prijmeni" type="text" class="form-control" value="<?= isset($_POST["prijmeni"]) ? $_POST["prijmeni"] : ucfirst($user["lastname"]) ?>" placeholder="Příjmení">
                            <label class="text-danger" style="<?= isset($errorarray["err2"]) ? "display: inline" : "display: none;" ?>">Špatný formát.</label>
                        </div>
                        <div class="col-md-6  mt-3">
                            <input required name="datum" min="<?= $date = date(("Y-m-d"), strtotime(date("Y-m-d") . '-120 years')); ?>" max="<?= $date = date(("Y-m-d"), strtotime(date("Y-m-d") . '-18 years')); ?>" type="date" class="form-control" value="<?= isset($_POST["datum"]) ? $_POST["datum"] : $user["birthdate"] ?>" placeholder="Datum narození">
                            <label class="text-danger" style="<?= isset($errorarray["err3"]) ? "display: inline" : "display: none;" ?>">Zadejte platné datum narození (dd.mm.rr).</label>
                            <label class="text-danger" style="<?= isset($errorarray["err14"]) ? "display: inline" : "display: none;" ?>">Uživatel musí být starší 18 let.</label>
                        </div>
                        <div class="col-md-6  mt-3">
                            <input required name="tel" type="text" class="form-control" value="<?= isset($_POST["tel"]) ? $_POST["tel"] : $user["phonenumber"] ?>" placeholder="Telefon">
                            <label class="text-danger" style="<?= isset($errorarray["err5"]) ? "display: inline" : "display: none;" ?>">Špatný formát.</label>
                            <label class="text-danger" style="<?= isset($errorarray["err15"]) ? "display: inline" : "display: none;" ?>">Telefon je již registrovaný.</label>

                        </div>

                        <div class="col-md-12  mt-3">
                            <input required name="email" type="text" class="form-control" value="<?= isset($_POST["email"]) ? $_POST["email"] : $user["email"] ?>" placeholder="Email">
                            <label class="text-danger" style="<?= isset($errorarray["err4"]) ? "display: inline" : "display: none;" ?>">Špatný formát.</label>
                            <label class="text-danger" style="<?= isset($errorarray["err13"]) ? "display: inline" : "display: none;" ?>">Email je již zaregistrovaný.</label>
                        </div>

                        <div class="col-md-8  mt-5">
                            <input required name="obec" type="text" class="form-control" value="<?= ucfirst(isset($_POST["obec"]) ? $_POST["obec"] : $address["city"]) ?>" placeholder="Obec">
                            <label class="text-danger" style="<?= isset($errorarray["err10"]) ? "display: inline" : "display: none;" ?>">Špatný formát.</label>
                        </div>

                        <div class="col-md-4  mt-md-5 mt-3">
                            <input required name="psc" type="text" class="form-control" value="<?= isset($_POST["psc"]) ? $_POST["psc"] : $address["postcode"] ?>" placeholder="PSČ">
                            <label class="text-danger" style="<?= isset($errorarray["err11"]) ? "display: inline" : "display: none;" ?>">Špatný formát.</label>
                        </div>

                        <div class="col-md-8 mt-3">
                            <input required name="ulice" type="text" class="form-control" value="<?= isset($_POST["ulice"]) ? $_POST["ulice"] : ucfirst($address["street"]) ?>" placeholder="Ulice">
                        </div>

                        <div class="col-md-4 mt-3">
                            <input required name="cp" type="text" class="form-control" value="<?= isset($_POST["cp"]) ? $_POST["cp"] : $address["house_number"] ?>" placeholder="Č.p.">
                            <label class="text-danger" style="<?= isset($errorarray["err9"]) ? "display: inline" : "display: none;" ?>">Špatný formát.</label>
                        </div>

                        <div class="col-12 mt-3">
                            <div class="form-check">
                                <input onclick="ischecked()" id="checkito" class="form-check-input" type="checkbox" name="checkbox" style="min-height: 15px; min-width: 15px;">
                                <label for="checkito" class="form-check-label">
                                    Upravit uživatele.
                                </label>
                            </div>
                            <label class="text-danger" style="<?= isset($errorarray["err12"]) ? "display: inline" : "display: none;" ?>">Nutno zaškrtnout.</label>
                        </div>

                        <div class="col-12 mt-3">
                            <button disabled="true" id="submitbutton" name="submit" class="btn barvabtnseda btn-dark w-100 p-2" type="submit"><strong>Upravit uživatele</strong></button>
                            <label class="text-danger" style="<?= isset($errorarray["err0"]) ? "display: inline" : "display: none;" ?>">Všechna pole musí být vyplněna.</label>

                        </div>

                    </div>
                </form>
            </div>
        </div>
    <?php else : ?>
        <?= '<h2 class="text-center">ID uživatele neexistuje</h2>' ?>
    <?php endif ?>



    <div class=" mt-5 mx-auto">
        <?php if (!empty($reservations)) : ?>
            <h2 class="text-center mb-5">HISTORIE REZERVACÍ</h2>
            <table class="table table-responsive-sm table-bordered text-center datatablereservationuser">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Vozidlo</th>
                        <th scope="col">Datum rezervace</th>
                        <th scope="col">Datum vypůjčení</th>
                        <th scope="col">Dohodnuté datum vrácení</th>
                        <th scope="col">Datum vrácení</th>
                        <th scope="col">Částka&nbsp(Kč)</th>
                        <th scope="col">Upravit</th>
                        <th scope="col">Odstranit</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($reservations as $reservation) : ?>
                        <tr>
                            <td scope="row"><?= $reservation["idreservation"] ?></td>
                            <td> <a class="link-unstyled" href="/vozovy_park/vozidlo?id=<?= $reservation["carid"] ?>"><button class="btn odkaztable"><strong> <?= $reservation["brand"] . " " . $reservation["model"]; ?></strong></button></a></td>
                            <td><?= $reservation["date_of_reservation"]; ?></td>
                            <td><?= $reservation["start_date"]; ?></td>
                            <td><?= $reservation["end_date"]; ?></td>
                            <td><?= (isset($reservation["return_date"]))  ? $reservation["return_date"] : 'Nevráceno'; ?></td>
                            <td><?= round($reservation["cost"]); ?></td>
                            <td style="padding: 0px;"> <a class="link-unstyled" href="/admin/rezervace/detail_rezervace?id=<?= $reservation["idreservation"] ?>"><button class="btn odkaztable"><strong>Upravit</strong></button></a></td>
                            <td style="padding: 0px;"><button id="<?= $reservation["idreservation"]; ?>" data-clicked="false" class="btn odkaztable deletereservation text-danger" data-toggle="modal" data-target="#modaldelete">Odstranit</button></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        <?php else : ?>
            <?= '<h2 class="text-center">ŽÁDNÉ REZERVACE</h2>' ?>
        <?php endif ?>
    </div>



    <div class="modal fade" id="modaldelete" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Odstranit rezervaci</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div id="deletemodal" class="modal-body">
                    <div class="row">
                        <div class="col-md-12">Skutečně chcete odstranit rezervaci?</div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" id="confirmdelete" class="btn" style="border: 1px solid rgb(172, 172, 172);">Odstranit</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Zavřít</button>
                </div>
            </div>
        </div>
    </div>

    <script defer src="../../assets/js/reservationbody.js"></script>
    <script defer src="../../../assets/js/checkboxcheck.js"></script>