<div style="height: 5rem;" class="col-md-12 d-flex justify-content-center mt-5">
    <h1 class="heading">Vyberte si to správné vozidlo</h1>
</div>

<!-- Start: Filter -->
<div class="filter container">
    <form method="POST" id="formfilter">
        <div class="row">
            <div class="col-lg-2 col-md-4 mt-3">
                <select name="pohon"  class="w-100">
                    <option value="*" <?= (isset($_POST['pohon']) && $_POST['pohon'] === '*') ? 'selected' : ''; ?>>Typ paliva</option>
                    <option value="Benzín" <?= (isset($_POST['pohon']) && $_POST['pohon'] === 'Benzín') ? 'selected' : ''; ?>>Benzín</option>
                    <option value="Nafta" <?= (isset($_POST['pohon']) && $_POST['pohon'] === 'Nafta') ? 'selected' : ''; ?>>Nafta</option>
                    <option value="Elektřina" <?= (isset($_POST['pohon']) && $_POST['pohon'] === 'Elektřina') ? 'selected' : ''; ?>>Elektřina</option>
                    <option value="LPG" <?= (isset($_POST['pohon']) && $_POST['pohon'] === 'LPG') ? 'selected' : ''; ?>>LPG</option>
                </select>
            </div>
            <div class="col-lg-2 col-md-4 mt-3" >
                <select name="razeni" class="w-100">
                    <option value="*" <?= (isset($_POST['razeni']) && $_POST['razeni'] === '*') ? 'selected' : ''; ?>>Způsob řazení</option>
                    <option value="Manuální" <?= (isset($_POST['razeni']) && $_POST['razeni'] === 'Manuální') ? 'selected' : ''; ?>>Manuální</option>
                    <option value="Automatické" <?= (isset($_POST['razeni']) && $_POST['razeni'] === 'Automatické') ? 'selected' : ''; ?>>Automat</option>
                </select>
            </div>
            <div class="col-lg-2 col-md-4 mt-3" >
                <select name="mista"  class="w-100">
                    <option value="*" <?= (isset($_POST['mista']) && $_POST['mista'] === '*') ? 'selected' : ''; ?>>Počet míst</option>
                    <option value="1-3" <?= (isset($_POST['mista']) && $_POST['mista'] === '1-3') ? 'selected' : ''; ?>>1-3</option>
                    <option value="4-5" <?= (isset($_POST['mista']) && $_POST['mista'] === '4-5') ? 'selected' : ''; ?>>4-5</option>
                    <option value="5-8" <?= (isset($_POST['mista']) && $_POST['mista'] === '5-8') ? 'selected' : ''; ?>>5-8</option>
                    <option value="8" <?= (isset($_POST['mista']) && $_POST['mista'] === '8+') ? 'selected' : ''; ?>>8+</option>
                </select>
            </div>
            <div class="col-lg-2 col-md-4 mt-3" >
                <input type="number" name="cenaod" class="form-control" value="<?= htmlspecialchars($_POST['cenaod'] ?? '', ENT_QUOTES); ?>" placeholder="Cena od"></input>
            </div>
            <div class="col-lg-2 col-md-4 mt-3" >
                <input type="number" name="cenado"class="form-control"  value="<?= htmlspecialchars($_POST['cenado'] ?? '', ENT_QUOTES); ?>" placeholder="Cena do"></input>
            </div>
            <div class="col-lg-2 col-md-4 mt-3" >
                <button name="filter" class="btn btn-dark btn-secondary w-100" type="submit">Filtrovat</button>
            </div>
        </div>
    </form>

</div>
<hr>

<script defer src="../assets/js/filter.js">

</script>