<div class="container mt-5 mx-auto">



  <?php if (!empty($reservations)) : ?>
    <h2 class="text-center mb-5">Historie rezervací</h2>
    <table class="table table-responsive-sm table-bordered text-center datatableuserreservation">
      <thead class="thead-dark">
        <tr>

          <th scope="col">Vozidlo</th>
          <th scope="col">Datum rezervace</th>
          <th scope="col">Datum vypůjčení</th>
          <th scope="col">Dohodnuté datum vrácení</th>
          <th scope="col">Datum vrácení</th>
          <th scope="col">Částka&nbsp;(Kč)</th>
          <th scope="col">Hodnocení</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($reservations as $reservation) : ?>

          <?php
          !isset($reservation["return_date"]) ? $reservation["stars"] = "-" : false;
          ?>
          <tr>

            <td scope="row"> <a class="link-unstyled" href="/vozovy_park/vozidlo?id=<?= $reservation["carid"] ?>"><button class="btn odkaztable"><strong> <?= $reservation["brand"] . " " . $reservation["model"]; ?></strong></button></a></td>
            <td><?= $reservation["date_of_reservation"]; ?></td>
            <td><?= $reservation["start_date"]; ?></td>
            <td><?= $reservation["end_date"]; ?></td>
            <td><?= (isset($reservation["return_date"]))  ? $reservation["return_date"] : 'Nevráceno'; ?></td>
            <td><?= round($reservation["cost"]) ?></td>
            <td><?= isset($reservation["stars"]) ? $reservation["stars"] . '&nbsp;<i class="fa fa-star fa-lg"></i>' :  '<button id="' . $reservation["carid"] . '" data-clicked="false" class="btn odkaztable addrating" data-toggle="modal" data-target="#modalrating">Ohodnotit</button>'; ?> </td>

          </tr>
        <?php endforeach ?>
      </tbody>
    </table>
  <?php else : ?>
    <?= '<h2 class="text-center">NEMÁTE ŽÁDNÉ REZERVACE</h2>' ?>
  <?php endif ?>
</div>


<div class="modal fade" id="modalrating" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Ohodnotit vozidlo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="ratingmodal" class="modal-body">
        <div class="row">
          <div class="col-md-12 getstars">
            <i value="1" id="hvezda1" data-rating="false" class="fa fa-star-o fa-lg">&nbsp;</i><i value="2" id="hvezda2" data-rating="false" class="fa fa-star-o fa-lg">&nbsp;</i><i value="3" id="hvezda3" data-rating="false" class="fa fa-star-o fa-lg">&nbsp;</i><i value="4" id="hvezda4" data-rating="false" class="fa fa-star-o fa-lg">&nbsp;</i><i value="5" id="hvezda5" data-rating="false" class="fa fa-star-o fa-lg"></i>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" id="confirmadd" class="btn" style="border: 1px solid rgb(172, 172, 172);">Ohodnotit</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Zavřít</button>
      </div>
    </div>
  </div>
</div>


<script defer src="/assets/js/rating.js"></script>

<script defer src="/assets/js/datatablesconfig.js"></script>