<div class="container">
    <div style="height: 5rem;" class="col-md-12 d-flex justify-content-center mt-5">
        <h1 class="heading">DriveOut</h1>
    </div>
    <div style="height: 5rem;" class="col-md-12 d-flex justify-content-center mt-5">
        <h2 class="heading">O nás</h2>
    </div>

    <p class="text-justify "><?= "Culpa ullamco deserunt dolor exercitation nulla non minim aliquip veniam anim deserunt Lorem aliquip fugiat. Tempor sint mollit aliqua aliqua sit ea qui mollit ex velit id fugiat amet culpa. Deserunt officia irure et mollit esse esse incididunt consectetur fugiat eiusmod deserunt dolor aliquip qui. Ipsum officia elit consectetur consequat dolore occaecat in consequat aute tempor pariatur ad. Ex exercitation magna aliquip consectetur incididunt consequat cupidatat proident do ea adipisicing. Cupidatat magna et adipisicing excepteur proident magna in occaecat." ?></p>
</div>